usethis::use_build_ignore("devtools_history.R")
usethis::use_package('stats')
usethis::use_package('coda')
usethis::use_vignette("how-to-use-malt")
usethis::use_vignette("Banana")
usethis::use_vignette("BayesianLogisticRegression")
